# config_lung.yaml
data_dir: "dataset_lung"
output_dir: 'experiments_lung'  # スペースを削除

# --- Dataset Settings ---
resize_shape: [224, 224]

# --- Dataloader Settings ---
batch_size: 4
num_workers: 2

# --- Model Settings ---
vit_model_name: 'google/vit-base-patch16-224-in21k'
vggt_learning_rate: 0.0002    # VGGTパス用のLR (2e-4)

# --- Training Settings ---
num_epochs: 200
learning_rate: 0.000005     # 5e-6（肺野は密なので少し下げる）
head_learning_rate: 0.001   # ヘッド側LR
seed: 42

# --- 3D Shape Settings ---
depth_head_lr: 0.0002        # 深度ヘッド専用LR
shape_consistency_weight: 0.5 # 形状一貫性の重み
depth_gradient_weight: 0.1   # 深度勾配損失の重み
depth_consistency_weight: 0.5 # 深度一貫性の重み
depth_warmup_epochs: 10      # 深度学習のウォームアップ期間

# --- Loss Weights ---
depth_loss_weight: 0.15      # 0.1から少し上げる
bev_grad_weight: 0.3         # 勾配損失の重み
dice_loss_weight: 0.2        # ソフトDice損失の重み

# --- BEV Settings ---
bev_target_mode: 'binary'    # まずbinaryで（密なので十分）
bev_gaussian_sigma: 2.0      # gaussianの場合用

# --- Advanced Training ---
use_shape_consistency: true   # 形状一貫性モジュールの使用
use_dilated_depth_head: true # 拡張畳み込みを使用した深度ヘッド
min_learning_rate: 1e-7      # Cosineスケジューラの最小LR

# --- Augmentation Settings ---
use_augmentation: false
rotation_degrees: 10
color_jitter_brightness: 0.2
color_jitter_contrast: 0.2
