# config.yaml

# --- Path Settings ---
data_dir: 'dataset'
output_dir: 'experiments' # 結果を保存する親ディレクトリ

# --- Dataset Settings ---
resize_shape: [224, 224]

# --- Dataloader Settings ---
batch_size: 4
num_workers: 2

# --- Model Settings ---
vit_model_name: 'google/vit-base-patch16-224-in21k'

# --- Training Settings ---
num_epochs: 1000
learning_rate: 0.00001  # 0.0001の10分の1に
seed: 42
# pos_weightはBEVタスクの不均衡データに対する重み
# 極端な不均衡（0.0184%が正例）に対処するため大きな値を設定
pos_weight: 200        # いまはFocal使用のため未使用（実験名にのみ反映）
depth_loss_weight: 0.0 # BEVに全集中

# --- Augmentation Settings ---
use_augmentation: false
rotation_degrees: 10
color_jitter_brightness: 0.2
color_jitter_contrast: 0.2

# --- BEV Settings ---
bev_target_mode: 'gaussian'
bev_gaussian_sigma: 3.0
bev_grad_weight: 0.5